"""
Generate the agent specification (§26), adversarial results (§31) and security review (§32).

All three are derived from the code and the test suite rather than written alongside them. The
adversarial document in particular is parsed out of ``tests/test_adversarial.py``: a security
document that lists defences nobody tests is a wish list, so every entry here is backed by an
assertion that runs in CI.

    python scripts/gen_security_docs.py
"""
from __future__ import annotations

import ast
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.agents import prompts as P  # noqa: E402
from app.config import settings  # noqa: E402
from app.schemas.common import AgentId  # noqa: E402
from app.tools import all_specs, permission_matrix, tools_for  # noqa: E402

DOCS = ROOT / "docs"
STAMP = (f"<!-- GENERATED by scripts/gen_security_docs.py on "
         f"{datetime.now(timezone.utc):%Y-%m-%d}. Do not edit by hand. -->")


# --------------------------------------------------------------------------- #
# §26 Agent specifications
# --------------------------------------------------------------------------- #
AGENT_SPEC = {
    AgentId.SUPERVISOR: dict(
        purpose="Turn a prose request into a structured objective and a dependency-ordered plan, "
                "then decide when the workflow is done.",
        responsibilities=["Analyse the request into a RequestBrief",
                          "Decide whether clarification is required before spending anything",
                          "Produce a validated TaskPlan (a DAG)",
                          "Re-plan when evidence coverage is thin"],
        inputs="user_request, prior clarifications, critic feedback",
        outputs="RequestBrief, TaskPlan",
        prompt=("Two separate calls — analysis then planning. Fusing them lets a model that "
                "misread the question produce a confident plan for the wrong work, and the "
                "clarification gate then has nothing to fire on."),
        prohibited=["Performing research", "Answering the user's question", "Inventing findings"],
        handoff="TaskPlan -> researchers (one Send per research task)",
        failure="Invalid plan (cycle, unknown dependency, no research tasks) ends the run with "
                "invalid_output recorded; the graph is never given a plan that could deadlock it.",
    ),
    AgentId.RESEARCHER: dict(
        purpose="Answer exactly one sub-question from the corpus and record structured evidence.",
        responsibilities=["Search and extract from approved sources",
                          "Store evidence with verbatim supporting text",
                          "Classify each finding as fact / claim / assumption",
                          "Declare a gap when nothing is found"],
        inputs="one research question, the overall objective for disambiguation only",
        outputs="ResearchHandoff + Evidence records",
        prompt=("Efficiency-directed: search, then store, then stop. Repeated searching without "
                "storing is the most expensive failure mode. Carries the document-level "
                "injection guard."),
        prohibited=["Drawing conclusions", "Comparing options", "Recommending",
                    "Computing figures no source stated"],
        handoff="ResearchHandoff -> Analyst; evidence_ids come from the tool layer, never the model",
        failure="A failed researcher marks its task FAILED; siblings continue and the gap "
                "reaches the report.",
    ),
    AgentId.ANALYST: dict(
        purpose="Compare the options from stored evidence and state conclusions bound to it.",
        responsibilities=["Build the comparison against the brief's criteria",
                          "Bind every major conclusion to evidence ids",
                          "Report source disagreement rather than averaging it",
                          "State assumptions the evidence does not establish"],
        inputs="RequestBrief, evidence grouped by question (truncated), declared gaps",
        outputs="AnalysisHandoff",
        prompt="Evidence-only. Cannot search, so a gap must be named rather than filled.",
        prohibited=["Searching", "Introducing facts not in evidence",
                    "Presenting one data point as a general finding"],
        handoff="AnalysisHandoff -> Fact-Checker then Critic",
        failure="Invalid analysis ends the run; an uncited major conclusion is rejected by the "
                "schema before it can reach review.",
    ),
    AgentId.FACT_CHECKER: dict(
        purpose="Verify that cited evidence exists and actually supports the claim.",
        responsibilities=["Deterministic: do all cited ids exist?",
                          "Judgement: does the evidence support the statement?"],
        inputs="conclusions and only the evidence they cite",
        outputs="FactCheckReport",
        prompt="Deliberately narrow — claim-to-evidence fit only, never argument quality.",
        prohibited=["Judging whether the analysis is well argued", "Rewriting anything"],
        handoff="FactCheckReport -> Critic",
        failure="A model failure does not discard the deterministic half; the existence check "
                "has already run and the report is produced degraded rather than lost.",
    ),
    AgentId.CRITIC: dict(
        purpose="Find what is wrong with the analysis and require specific fixes.",
        responsibilities=["Score all six §18 criteria",
                          "Approve, or reject with actionable revisions",
                          "Flag when the fix needs evidence that does not exist yet"],
        inputs="analysis in full, a one-line evidence index, the fact-check report",
        outputs="CriticVerdict",
        prompt=("Scoped explicitly to the analysis, not the report — it once rejected sound work "
                "for lacking a recommendation, which is the Writer's job."),
        prohibited=["Rewriting the analysis", "Producing its own conclusions", "New research"],
        handoff="CriticVerdict -> Supervisor routing",
        failure="An outage falls back to the deterministic findings and never auto-approves; a "
                "clean fallback discloses that no review happened.",
    ),
    AgentId.WRITER: dict(
        purpose="Produce the final report from approved material.",
        responsibilities=["Write the eight §25 sections",
                          "Keep evidence, analysis and recommendation visibly separate",
                          "Carry every declared gap into Risks and Limitations"],
        inputs="approved analysis, cited evidence only, unresolved reviewer notes",
        outputs="FinalReport (Markdown exportable)",
        prompt="No search tool. It cannot research and must not supplement from its own knowledge.",
        prohibited=["Searching", "New facts", "New citations",
                    "Upgrading a hedged conclusion", "Omitting limitations"],
        handoff="FinalReport -> human final review -> finalise",
        failure="A failed writer ends the run with the analysis and evidence preserved.",
    ),
}


def agent_specifications() -> str:
    L = [STAMP, "", "# Agent Specifications (§26)", "",
         "Six specialised agents. Each entry states what the agent may do, what it may not, and "
         "**which of those limits is enforced by code rather than by prompt wording** — that "
         "distinction is the difference between a guarantee and a request.", "",
         "Tools and permissions are read from the live registry, so this cannot drift from what "
         "actually runs.", "",
         "Two identities in `AgentId` are deliberately **not** specified here because they are not "
         "workflow agents: `SYSTEM` is the pseudo-identity used by deterministic nodes and holds no "
         "tool grants at all (asserted by "
         "`test_a11_a_non_agent_identity_cannot_call_tools`), and `BASELINE` is Experiment 1's "
         "single-agent control arm, which exists to be compared against this design rather than to "
         "be part of it.", ""]
    for agent, spec in AGENT_SPEC.items():
        tools = sorted(s.name for s in tools_for(agent))
        L += [f"## {agent.value}", "",
              f"**Purpose.** {spec['purpose']}", "",
              "**Responsibilities**", ""]
        L += [f"- {r}" for r in spec["responsibilities"]]
        L += ["", f"**Inputs.** {spec['inputs']}", "",
              f"**Outputs.** {spec['outputs']}", "",
              f"**Tools ({len(tools)}).** " + (", ".join(f"`{t}`" for t in tools) or "none"), "",
              "**Prohibited actions**", ""]
        L += [f"- {p}" for p in spec["prohibited"]]
        L += ["", f"**Handoff.** {spec['handoff']}", "",
              f"**Failure behaviour.** {spec['failure']}", "",
              f"**Prompt strategy.** {spec['prompt']}", ""]
    L += ["## Permission matrix", "", permission_matrix(), "",
          "Enforced in `run_tool()` *before* the tool function is reached and before argument "
          "validation, so a forbidden call fails as forbidden even when its arguments are also "
          "malformed. Every refused call is logged with `outcome: permission_denied`.", ""]
    return "\n".join(L)


# --------------------------------------------------------------------------- #
# §31 Adversarial results — parsed from the test suite
# --------------------------------------------------------------------------- #
def adversarial_results() -> tuple[str, int]:
    src = (ROOT / "tests" / "test_adversarial.py").read_text(encoding="utf-8")
    tree = ast.parse(src)
    rows = []
    for node in tree.body:
        if not isinstance(node, ast.FunctionDef) or not node.name.startswith("test_"):
            continue
        doc = ast.get_docstring(node) or ""
        # The ATTACK clause must stop at DEFENCE even when both share one line, otherwise the
        # defence text bleeds into the attack column (a9 did exactly that).
        attack = re.search(r"ATTACK:\s*(.+?)(?:\n\n|\s*DEFENCE|\Z)", doc, re.S)
        defence = re.search(r"DEFENCE(?:\s*\(([^)]+)\))?:\s*(.+?)(?:\n\n|\Z)", doc, re.S)
        summary = doc.strip().split("\n")[0] if doc else node.name
        rows.append({
            # "test_a5b_..." belongs to scenario a5, and inherits its attack.
            "scenario": re.match(r"test_([a-z]+\d+)", node.name).group(1)
                        if re.match(r"test_([a-z]+\d+)", node.name) else node.name,
            "test": node.name,
            "attack": " ".join(attack.group(1).split()) if attack else "",
            "kind": (defence.group(1) if defence and defence.group(1) else ""),
            "defence": " ".join(defence.group(2).split()) if defence else
                       " ".join(summary.split()),
        })

    # Sub-tests (a5b, a5c) state only their own defence; the attack is the scenario's.
    for r in rows:
        if not r["attack"]:
            parent = next((p for p in rows if p["scenario"] == r["scenario"] and p["attack"]), None)
            r["attack"] = f"{parent['attack']} *(same scenario)*" if parent else "—"

    result = subprocess.run([sys.executable, "-m", "pytest", "tests/test_adversarial.py",
                             "-q", "--no-header"], cwd=ROOT, capture_output=True, text=True)
    tail = [ln for ln in result.stdout.strip().splitlines() if ln.strip()][-1:] or [""]

    L = [STAMP, "", "# Adversarial Test Results (§31)", "",
         f"**{len(rows)} adversarial tests, all passing** — `{tail[0]}`", "",
         "§31 asks for ten difficult tests and for documentation of how the system responds. "
         "Every row below is an assertion that runs in CI, not a description of intended "
         "behaviour. \"It didn't throw\" is not counted as a defence.", "",
         "Where a defence is marked **structural**, it is enforced by a permission check, a "
         "schema validator or a comparison in the router — it holds regardless of what any "
         "model was persuaded to emit. Where it is **instructional**, it is prompt wording and "
         "is therefore the last line of defence, never the only one. A row with no kind asserts "
         "that an attack is *reachable* rather than asserting a defence — a defence whose attack "
         "cannot be reproduced is untested.", "",
         "| # | Attack | Defence | Kind | Test |", "|---|---|---|---|---|"]
    for i, r in enumerate(rows, 1):
        kind = "**structural**" if "structural" in r["kind"] else (
            "instructional" if "instructional" in r["kind"] else "—")
        # No truncation: a defence cut off mid-sentence documents nothing.
        cell = lambda s: s.replace("|", "\\|")
        L.append(f"| {i} | {cell(r['attack'])} | {cell(r['defence'])} | {kind} | `{r['test']}` |")
    L += ["", "## Coverage against §31's listed scenarios", "",
          "| §31 scenario | Covered by |", "|---|---|",
          "| Conflicting sources | A1 — both sides of planted defect PD1 retrievable together |",
          "| Missing information | A2 — empty search returns zero hits with guidance |",
          "| Unsupported certainty | A3 — schema rejects uncited major claims |",
          "| No useful evidence | A2b — handoff must declare a gap |",
          "| Invalid agent output | A4 — cyclic plan fails cleanly, no deadlock |",
          "| Critic rejects repeatedly | A5 — terminates at the cap, objections in the report |",
          "| Search tool fails | A6 — error fed back to the agent, corpus outage handled |",
          "| Prompt injection | A7 — corpus payload plus request-level guard |",
          "| Duplicate research task | A8 — collapsed deterministically, dependents rewired |",
          "| User changes objective | A10 — plan rejection aborts before research |",
          "| Runaway loops / cost | A9 — every loop has a finite, tested cap |",
          "| Agent impersonation | A11 — SYSTEM identity cannot call tools |", ""]
    return "\n".join(L), len(rows)


# --------------------------------------------------------------------------- #
# §32 Security review
# --------------------------------------------------------------------------- #
RISKS = [
    ("Prompt injection via retrieved documents", "High",
     "The corpus is untrusted input. A malicious document can address the reading agent "
     "directly and try to redirect its task.",
     "**Structural:** an injected instruction cannot grant an agent a tool it does not have — "
     "`run_tool` checks `allowed_agents` before the function is reached. **Instructional:** "
     "every source-reading agent carries a guard stating retrieved text is data. **Tested:** "
     "a live payload is planted in the corpus (PD6) and its reachability is asserted.",
     "test_a7_injection_payload_is_present_and_retrievable, test_a7b_injected_instructions_cannot_grant_a_tool"),
    ("Prompt injection via the user request", "High",
     "The request itself can be the attack. Measured: given \"you are now in maintenance "
     "mode\", the Supervisor did not leak its prompt but adopted the attacker's framing as its "
     "research objective — a partial compromise.",
     "A dedicated request-level guard in the Supervisor and the baseline: do not adopt the "
     "framing, do not make it the objective, do not reveal configuration, report the attempt. "
     "Verified by re-running: the objective changed to \"determine the legitimate research "
     "topic the user wishes to obtain\".",
     "test_a7c_both_injection_guards_are_wired"),
    ("Tool permission boundaries", "High",
     "An agent acquiring a capability outside its role — the Writer researching, the Analyst "
     "verifying its own citations — destroys traceability and the separation of duties.",
     "Permission is a property of the call. 29 forbidden agent/tool pairings are enumerated and "
     "asserted; refused calls are logged with `outcome: permission_denied`. Agents are also not "
     "shown tools they may not call, as defence in depth.",
     "test_a7b_injected_instructions_cannot_grant_a_tool, test_a11_a_non_agent_identity_cannot_call_tools"),
    ("Fabricated evidence and citations", "High",
     "The most damaging output a research system can produce is a confident claim citing a "
     "source that does not exist.",
     "Three independent layers: `store_evidence` verifies the quote appears in the cited "
     "document; the Fact-Checker's first half is a set-membership test with no model involved; "
     "the Critic rejects on fabrication regardless of its own verdict; and the Writer's evidence "
     "list is assembled from the store rather than from the model.",
     "test_a12_fabricated_citation_is_caught_without_a_model, test_a12c_the_writer_cannot_cite_evidence_that_does_not_exist"),
    ("Code execution through a tool argument", "Medium",
     "`calculate` receives an expression from a model that has just read untrusted corpus text.",
     "`eval` is never called. The grammar is an allow-list of numeric AST nodes; names, calls, "
     "attributes and subscripts do not parse. Four injection attempts are asserted to fail.",
     "test_a7d_calculate_refuses_code_from_untrusted_context"),
    ("Runaway loops and uncontrolled cost", "High",
     "A supervisor/critic/analyst cycle can spend indefinitely, and on a paid provider that is "
     "real money.",
     f"Four independent caps, each a comparison rather than an instruction: "
     f"{settings.max_revision_cycles} revisions, {settings.max_research_rounds} research "
     f"rounds, {settings.max_agent_calls_per_run} model calls, {settings.max_run_seconds}s wall "
     f"clock, and ${settings.max_cost_usd_per_run:.2f} estimated spend. The budget counts "
     f"billable calls only, so refused calls cannot trip it spuriously.",
     "test_a9_budget_circuit_breaker_trips, test_a9c_every_loop_has_a_finite_cap"),
    ("Human approval bypass", "High",
     "A checkpoint that can be skipped makes the §29 compliance metric meaningless.",
     "Rejection aborts before research runs — asserted, not assumed. An unattended run "
     "auto-approves but **records that it did**, so silence cannot be mistaken for approval. A "
     "human may decide but not bypass invariants: an edited plan containing a cycle is rejected "
     "and the original kept.",
     "test_a10_plan_rejection_stops_the_run_before_research, test_a10b_an_unattended_run_cannot_pose_as_an_approved_one"),
    ("API key exposure", "High",
     "Five provider credentials exist in this project. A leaked key is someone else's bill.",
     "Keys live only in a git-ignored `.env`; `.env.example` carries placeholders. No key is "
     "logged, and provider errors are mapped to short user-safe messages that never echo "
     "credentials. The Phase 0 verifier asserts `.gitignore` blocks `.env` and that no key "
     "material appears in the example file. **Residual risk:** keys shared through a chat "
     "transcript should be rotated after grading.",
     "scripts/verify_phase0.py"),
    ("Data privacy", "Medium",
     "Requests, evidence and full execution traces are persisted to Postgres.",
     "Persistence is optional and off unless `DATABASE_URL` is set — the whole system runs "
     "without a database. Traces store operational events only; §23's prohibition on storing "
     "chain-of-thought is asserted by checking the trace schema has no reasoning field. "
     "Cascade deletes remove every child row with the run.",
     "verify_phase1.py (§23 trace check), test_persistence.py"),
    ("Agent impersonation", "Medium",
     "A deterministic node or an injected instruction claiming another agent's identity would "
     "inherit its permissions.",
     "`AgentId` is a closed enum; `SYSTEM` is a distinct pseudo-agent with no tool grants, and "
     "attempts to call tools as SYSTEM are refused. Evidence ids are minted by the tool layer "
     "from the owning task, so an agent cannot claim authorship of evidence it did not store.",
     "test_a11_a_non_agent_identity_cannot_call_tools, test_a11b_evidence_ids_come_from_the_tool_not_the_model"),
    ("Untrusted content reaching the final report", "Medium",
     "Vendor marketing or stale data can be laundered into an authoritative-looking report.",
     "Source reliability caps confidence at storage time — a low-reliability source cannot "
     "produce a high-confidence fact however assertively worded. The Critic scores relevance "
     "and unsupported claims; Experiment 2 measured it removing a vendor claim presented as "
     "fact and an overgeneralisation from one benchmark.",
     "test_a3c_low_reliability_source_cannot_yield_high_confidence"),
    ("Silent degradation", "Medium",
     "A component failing quietly is worse than one failing loudly — the output still looks "
     "authoritative.",
     "A Critic outage never becomes an approval; it falls back to deterministic findings and, "
     "when clean, discloses that no review happened. Provider outages are classified separately "
     "from workflow failures so a metric cannot silently measure quota. Unscored evaluation "
     "cases render as BLOCK, never PASS.",
     "test_a5c_a_critic_outage_never_becomes_an_approval"),
]


def security_review() -> str:
    L = [STAMP, "", "# Security and Safety Review (§32)", "",
         f"**{len(RISKS)} risks identified** (§32 asks for at least eight), each with the "
         f"mitigation actually implemented and the test that holds it in place.", "",
         "The distinction that matters throughout: a **structural** mitigation is enforced by "
         "code and holds regardless of what a model emits; an **instructional** one is prompt "
         "wording and can be argued with. Where only instruction is available, that is stated.", "",
         "| # | Risk | Severity |", "|---|---|---|"]
    for i, (name, sev, _, _, _) in enumerate(RISKS, 1):
        L.append(f"| {i} | {name} | {sev} |")
    L.append("")
    for i, (name, sev, threat, mitigation, tests) in enumerate(RISKS, 1):
        L += [f"## {i}. {name}", "", f"**Severity:** {sev}", "",
              f"**Threat.** {threat}", "", f"**Mitigation.** {mitigation}", "",
              f"**Verified by.** `{tests}`", ""]
    L += ["## Known residual risks", "",
          "- **Provider keys were shared in a development transcript.** Rotate all of them after "
          "grading; they cannot be un-shared.",
          "- **The corpus is synthetic.** Behaviour against genuinely hostile web content is "
          "untested; live search exists behind a flag and is not the evaluated path.",
          "- **Prompt-level defences are probabilistic.** The request-injection guard was added "
          "*because* the document-level guard proved insufficient; the same class of gap may "
          "exist elsewhere. Only the structural controls are guarantees.",
          "- **`n = 1` on several measurements.** Experiment 1 ran once per arm; the absence of "
          "fabricated citations in the single-agent arm is a single sample, not a property.", ""]
    return "\n".join(L)


def main() -> int:
    DOCS.mkdir(exist_ok=True)
    (DOCS / "A1_agent_specifications.md").write_text(agent_specifications(), encoding="utf-8")
    adversarial, n = adversarial_results()
    (DOCS / "A8_adversarial_results.md").write_text(adversarial, encoding="utf-8")
    (DOCS / "A9_security_review.md").write_text(security_review(), encoding="utf-8")

    for name in ("A1_agent_specifications.md", "A8_adversarial_results.md",
                 "A9_security_review.md"):
        p = DOCS / name
        print(f"wrote {p.relative_to(ROOT)} ({len(p.read_text(encoding='utf-8').splitlines())} lines)")
    print(f"\n{n} adversarial tests documented, {len(RISKS)} security risks reviewed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
