"""
Generate the state and handoff specification docs **from the live code**.

§27 asks for a state table and §17 for documented handoff schemas. Hand-written versions of
both drift the moment a field changes, and a spec that contradicts the code is worse than no
spec — it misleads a reviewer who trusts it. Week 3 used this same generate-from-code approach
for its tool spec and it was the only doc that stayed accurate all week.

    python scripts/gen_specs.py
"""
from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from pydantic import BaseModel  # noqa: E402

from app.graph.state import PARALLEL_WRITE_CHANNELS, permissions_table  # noqa: E402
from app.schemas.handoffs import (  # noqa: E402
    AnalysisHandoff,
    CriticVerdict,
    FactCheckReport,
    ResearchHandoff,
)
from app.schemas.reports import FinalReport  # noqa: E402
from app.schemas.request import RequestBrief  # noqa: E402
from app.schemas.tasks import TaskPlan  # noqa: E402

STAMP = f"<!-- GENERATED by scripts/gen_specs.py on {datetime.now(timezone.utc):%Y-%m-%d}. Do not edit by hand. -->"

HANDOFFS = [
    ("Supervisor → all", RequestBrief, "Structured form of the user request (§9)."),
    ("Supervisor → Researchers", TaskPlan, "Dependency-ordered task plan (§11). Validated as a DAG."),
    ("Researcher → Analyst", ResearchHandoff, "One per research task; accumulates additively under the parallel fan-out."),
    ("Analyst → Fact-Checker / Critic", AnalysisHandoff, "Conclusions bound to the evidence supporting them."),
    ("Fact-Checker → Critic", FactCheckReport, "Citation integrity: deterministic existence check plus model judgement."),
    ("Critic → Supervisor", CriticVerdict, "Approve/reject with actionable revisions."),
    ("Writer → User", FinalReport, "The §25 deliverable."),
]


def field_table(model: type[BaseModel]) -> str:
    rows = ["| Field | Type | Required | Description |", "|---|---|---|---|"]
    for name, f in model.model_fields.items():
        ann = f.annotation
        type_name = getattr(ann, "__name__", None) or str(ann).replace("typing.", "")
        type_name = type_name.replace("app.schemas.", "")
        desc = (f.description or "").replace("\n", " ").replace("|", "\\|")
        rows.append(f"| `{name}` | `{type_name}` | {'yes' if f.is_required() else 'no'} | {desc} |")
    return "\n".join(rows)


def validators(model: type[BaseModel]) -> list[str]:
    """Pull the docstring first lines of model validators — the enforced invariants."""
    out = []
    for attr in vars(model).values():
        fn = getattr(attr, "__func__", None) or getattr(attr, "wrapped", None)
        if callable(fn) and fn.__doc__ and fn.__name__.startswith("_"):
            out.append(fn.__doc__.strip().split("\n")[0])
    return out


def main() -> int:
    docs = ROOT / "docs"
    docs.mkdir(exist_ok=True)

    # ---------------------------------------------------------------- state
    state_md = [
        STAMP, "", "# Workflow State Specification (§16, §27)", "",
        "One typed state object is the only channel between agents. No agent receives another",
        "agent's chat history; each reads the named fields it is entitled to and writes only the",
        "fields it owns.", "",
        "## Field permissions", "",
        permissions_table(), "",
        "## Parallel-write channels", "",
        "LangGraph merges partial states returned by concurrently running nodes. A channel written",
        "by two branches in the same superstep **must** declare a reducer, or LangGraph raises",
        "`InvalidUpdateError` at runtime. These channels are written by the researcher fan-out and",
        "each carries a reducer:", "",
    ]
    state_md += [f"- `{c}`" for c in sorted(PARALLEL_WRITE_CHANNELS)]
    state_md += [
        "",
        "Every other channel is written by exactly one sequential node. That is deliberate: an",
        "accidental write from inside the fan-out fails loudly instead of silently discarding a",
        "sibling branch's work.", "",
        "`tests/test_schemas.py::test_every_parallel_channel_has_a_reducer` asserts this, and",
        "`::test_langgraph_actually_merges_parallel_writes` proves it end to end against a real",
        "`Send()` fan-out.", "",
        "## Evidence id allocation", "",
        "Parallel researchers cannot share a counter — each branch sees its own copy of state, so",
        "two branches both reading \"next id is E4\" would mint the same id and one finding would be",
        "lost. Ids are instead derived from the owning task (`R2`'s third finding is always `E203`),",
        "which needs no coordination and makes the trace self-describing.", "",
    ]
    (docs / "A2_state_specification.md").write_text("\n".join(state_md), encoding="utf-8")

    # ------------------------------------------------------------- handoffs
    hand_md = [
        STAMP, "", "# Agent Handoff Contracts (§17)", "",
        "Every transfer between agents is a validated Pydantic object, never a chat transcript.",
        "Invariants below are enforced by model validators, so they cannot be bypassed by prompt",
        "wording — each has a test proving it rejects bad input.", "",
        "## Workflow order", "", "```",
        "Researcher   -> Analyst        ResearchHandoff",
        "Analyst      -> FactChecker    AnalysisHandoff",
        "FactChecker  -> Critic         FactCheckReport",
        "Critic       -> Supervisor     CriticVerdict",
        "Supervisor   -> Writer         AnalysisHandoff + CriticVerdict (already validated)",
        "Writer       -> User           FinalReport",
        "```", "",
    ]
    for label, model, note in HANDOFFS:
        hand_md += [f"## {label} — `{model.__name__}`", "", note, "", field_table(model), ""]
        inv = validators(model)
        if inv:
            hand_md += ["**Enforced invariants:**", ""] + [f"- {i}" for i in inv] + [""]
    (docs / "A3_handoff_contracts.md").write_text("\n".join(hand_md), encoding="utf-8")

    # ----------------------------------------------------------------- tools
    from app.schemas.common import AgentId
    from app.tools import all_specs, permission_matrix, tools_for

    tool_md = [
        STAMP, "", "# Tool Specification and Permission Boundaries (§13, §14)", "",
        "Permission is a property of the call, not of a prompt. `run_tool()` takes an `agent_id`",
        "and checks it against the tool's `allowed_agents` **before** the tool function is",
        "reached, so a forbidden call cannot succeed whatever the model was persuaded to emit.",
        "This matters here because the corpus deliberately contains a prompt-injection payload:",
        "an injected instruction cannot grant an agent a tool it does not have.", "",
        "Every refused call is written to the audit log with `outcome: permission_denied`.", "",
        "## Permission matrix", "",
        permission_matrix(), "",
        "## Tools by agent", "",
    ]
    for agent in sorted(AgentId.llm_agents(), key=lambda a: a.value):
        names = sorted(s.name for s in tools_for(agent))
        tool_md.append(f"- **{agent.value}** ({len(names)}): " + ", ".join(f"`{n}`" for n in names))
    tool_md += ["", "## Tool details", ""]

    for spec in sorted(all_specs(), key=lambda s: s.name):
        allowed = ", ".join(sorted(a.value for a in spec.allowed_agents))
        tool_md += [
            f"### `{spec.name}`", "",
            spec.description, "",
            f"- **Permitted agents:** {allowed}",
            f"- **Writes durable state:** {'yes' if spec.is_write else 'no'}", "",
            f"**Why these agents and no others.** {spec.rationale}", "",
            "**Input**", "", field_table(spec.input_model), "",
            "**Output**", "", field_table(spec.output_model), "",
        ]
    (docs / "A4_tool_specification.md").write_text("\n".join(tool_md), encoding="utf-8")

    # ---------------------------------------------------------- architecture
    from app.config import settings
    from app.graph.workflow import EDGES, describe_topology

    arch = [
        STAMP, "", "# Workflow Architecture (§7, §8, §18, §22)", "",
        "Generated from the compiled graph, so the diagram cannot drift from the code that runs.",
        "", "## Topology", "", "```mermaid", "flowchart TD",
    ]
    # Deterministic nodes get a distinct shape so the diagram shows, at a glance, where the
    # system spends a model call and where it does not.
    SHAPES = {
        "__start__": '(["User request"])',
        "__end__": '(["End"])',
        "intake": '[["intake<br/>deterministic"]]',
        "evidence_gate": '[["evidence gate<br/>deterministic"]]',
        "revision": '[["revision counter<br/>deterministic"]]',
        "plan_approval": '{{"human checkpoint"}}',
    }

    # `end` is a reserved keyword in mermaid — a node id of `end` silently breaks the whole
    # diagram, and LangGraph's terminal node is literally named `__end__`. Rename both sentinels
    # rather than stripping underscores blindly.
    IDS = {"__start__": "req", "__end__": "done"}

    def node_id(node: str) -> str:
        return IDS.get(node, node)

    def node_line(node: str) -> str:
        shape = SHAPES.get(node) or '["' + node + '"]'
        return "    " + node_id(node) + shape

    seen: set[str] = set()
    for src, dst, note in EDGES:
        for node in (src, dst):
            if node not in seen:
                arch.append(node_line(node))
                seen.add(node)
        arrow = "-->|" + note + "|" if note else "-->"
        arch.append("    " + node_id(src) + " " + arrow + " " + node_id(dst))
    arch += ["```", "", "## Edges", "", "```", describe_topology(), "```", ""]

    arch += [
        "## Why the workflow always terminates", "",
        "Three counters, each compared in `app/graph/routing.py`. Every one increases",
        "monotonically, and every comparison routes **forward** once its cap is met, so no cycle",
        "can repeat indefinitely.", "",
        "| Counter | Bounds | Cap |", "|---|---|---|",
        f"| `revision_count` | the Critic to Analyst loop | {settings.max_revision_cycles} |",
        f"| `research_round` | re-planning when evidence is thin | {settings.max_research_rounds} |",
        f"| `billable_calls` | everything else | {settings.max_agent_calls_per_run} |",
        f"| wall clock | a hung run | {settings.max_run_seconds}s |", "",
        "`tests/test_workflow.py::test_workflow_terminates_when_critic_rejects_forever` asserts",
        "this against a Critic scripted to reject ten times in a row.", "",
        "## Deterministic versus agentic", "",
        "Routing never calls a model. Coverage scoring, budget enforcement, citation existence,",
        "duplicate-task detection and revision counting are plain Python; a model is spent only",
        "where judgement is genuinely required.", "",
        "## Failure handling (§22)", "",
        "| Failure | Response |", "|---|---|",
        "| Agent returns invalid output | Reported as a failed `AgentOutcome`; the run ends cleanly with the error recorded |",
        "| One researcher fails | Its task is marked FAILED, siblings continue, the gap reaches the report |",
        "| Model API failure | Cross-provider fallback; a stated `retry-after` is honoured, capped |",
        "| Daily quota exhausted | Distinct from a rate limit — the chain moves on rather than waiting |",
        "| Critic unavailable | Falls back to the Fact-Checker's deterministic findings; never auto-approves |",
        "| Duplicate research tasks | Collapsed before execution by string similarity |",
        "| Dependency cycle in a plan | Rejected at construction, before the graph can deadlock |",
        "| Database unreachable | Persistence no-ops; the run still completes |",
        "| Runaway loop | Revision, research-round, call and wall-clock caps |", "",
    ]
    (docs / "A5_architecture.md").write_text("\n".join(arch), encoding="utf-8")

    for name in ("A2_state_specification.md", "A3_handoff_contracts.md",
                 "A4_tool_specification.md", "A5_architecture.md"):
        p = docs / name
        print(f"wrote {p.relative_to(ROOT)}  ({len(p.read_text(encoding='utf-8').splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
